services:
  postgres:
    ports:
      - '${DB_PORT:-5432}:5432'
    restart: 'no'

  app:
    build:
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run start:dev
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      TSC_WATCHFILE: UsePollingDelay
    restart: 'no'
