export const ERROR_CODES = {
  INVALID_REQUEST: 'invalidRequest',
  UNAUTHENTICATED: 'unauthenticated',
  FORBIDDEN: 'forbidden',
  ITEM_NOT_FOUND: 'itemNotFound',
  DUPLICATE_RESOURCE: 'duplicateResource',
  INTERNAL_SERVER_ERROR: 'internalServerError',
  UNKNOWN_ERROR: 'error',
  CATEGORY: {
    NAME_EXISTS: 'categoryNameExists',
    NOT_FOUND: 'categoryNotFound',
  },
  USER: {
    EMAIL_EXISTS: 'userEmailExists',
    CLERK_ID_EXISTS: 'userClerkIdExists',
    NOT_FOUND: 'userNotFound',
  },
  PRODUCT: {
    NAME_EXISTS: 'productNameExists',
    NOT_FOUND: 'productNotFound',
    PRIMARY_IMAGE_REQUIRED: 'primaryImageRequired',
    DUPLICATE_SORT_ORDERS: 'duplicateSortOrders',
  },
  PRODUCT_VARIANT: {
    SKU_EXISTS: 'productVariantSkuExists',
    NOT_FOUND: 'productVariantNotFound',
  },
  PRODUCT_IMAGE: {
    NOT_FOUND: 'productImageNotFound',
  },
  PAGINATION: {
    PAGE_OUT_OF_RANGE: 'pageOutOfRange',
  },
  VALIDATION: {
    NOT_EMPTY: 'isNotEmpty',
    IS_INT: 'isInt',
    IS_NUMBER: 'isNumber',
    IS_BOOLEAN: 'isBoolean',
    IS_ARRAY: 'isArray',
    IS_STRING: 'isString',
    IS_POSITIVE: 'isPositive',
    MIN: 'min',
    MIN_LENGTH: 'minLength',
    MAX: 'max',
    ARRAY_MIN_SIZE: 'arrayMinSize',
    ARRAY_MAX_SIZE: 'arrayMaxSize',
    MAX_LENGTH: 'maxLength',
    IS_UUID: 'isUuid',
    IS_URL: 'isUrl',
    IS_ENUM: 'isEnum',
    INVALID: 'invalid',
  },
} as const;
